# Project information
site_name: Interview Icebraker
site_url: https://interview-icebraker.readthedocs.io/en/latest/
site_author: Hasan Ozdemir
site_description: "This repository contains a comprehensive list of interview questions that can assist you in securing your dream job"

# Repository
repo_url: https://github.com/hasanozdem1r/interview-icebraker

# Copyright
copyright: "Interview Icebraker is licensed under the <a href='https://github.com/hasanozdem1r/interview-icebraker/blob/master/LICENSE'>Apache License 2.0</a>"


theme:
  name: null
  disable_nav_previous_next: true
  # Turn off the footer entirely
  disable_footer: true
  custom_dir: 'cinder'
  # snytax highlighting
  colorscheme: dracula
  favicon: img/favicon.ico

nav:
    - HOME: index.md
    - PYTHON: python.md
    - SQL: sql.md
    - DEVOPS: devops.md 
    - AWS: amazon_web_services.md

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
  collapse_toc: false

  